spring.application.name=JcDecorarSite
spring.docker.compose.enabled=false
# ===============================
# DATABASE - NEON POSTGRESQL
# ===============================

spring.datasource.url=jdbc:postgresql://ep-sparkling-lake-ays53zjj-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require

spring.datasource.username=neondb_owner

spring.datasource.password=npg_x1tmFzH8aKZk


# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# ===============================
# JWT
# ===============================

# futuramente colocar aqui a chave fixa
jwt.secret=123